### ISSUE TITLE
Data imputation for NA

### ISSUE THREAD

**Issue by ajcammack** [ndcn/soda-ndcn#140]
On NA imputation, missing values are being replaced by very small values, even when set to "keep NA." Because of this, fold changes and other statistics are incorrect for any lipid species for which there is a missing value in a replicate of a group.

**Comment by dolivierj** [comment]
Changed in patch 0.5.5:
Improved imputation to work on groups instead of batches, now imputing each missing feature for a group by that group's min/mean/median/max if non-missing values are above a certain number.
Choice to skip imputation now clearly keeps values as NA, and will be displayed as such in plots
